<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" 
    xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns="http://fedex.com/ws/rate/v28">
    <SOAP-ENV:Body>
        <RateRequest> 
            <WebAuthenticationDetail> 
                <ParentCredential> 
                    <Key>{$request.api_key}</Key> 
                    <Password>{$request.password}</Password> 
                </ParentCredential> 
                <UserCredential> 
                    <Key>{$request.api_key}</Key> 
                    <Password>{$request.password}</Password> 
                </UserCredential> 
            </WebAuthenticationDetail> 
            <ClientDetail> 
                <AccountNumber>{$request.account}</AccountNumber> 
                <MeterNumber>{$request.meter}</MeterNumber> 
            </ClientDetail> 
            <TransactionDetail> 
                <CustomerTransactionId>{$request.txn_id}</CustomerTransactionId> 
            </TransactionDetail> 
            <Version> 
                <ServiceId>crs</ServiceId> 
                <Major>28</Major> 
                <Intermediate>0</Intermediate> 
                <Minor>0</Minor>
            </Version> 
            <RequestedShipment> 
                <DropoffType>{$request.dropoff_type}</DropoffType> 
                <ServiceType>{$request.service}</ServiceType> 
                <PackagingType>{$request.packaging_type}</PackagingType> 
                <TotalWeight> 
                    <Units>{$request.weight_units}</Units> 
                    <Value>{$request.weight}</Value> 
                </TotalWeight> 
                <Shipper> 
                    <Contact>
                        <CompanyName>{$request.shipper_name}</CompanyName> 
                        <PhoneNumber>{$request.phone_from}</PhoneNumber> 
                    </Contact>
                    <Address> 
                        <StreetLines>{$request.address_from}</StreetLines>
                        <City>{$request.city_from}</City> 
                        <StateOrProvinceCode>{$request.state_from}</StateOrProvinceCode> 
                        <PostalCode>{$request.postcode_from}</PostalCode> 
                        <CountryCode>{$request.country_from}</CountryCode> 
                    </Address>
                </Shipper> 
                <Recipient> 
                    <Contact> 
                        <PersonName>{$request.recipient_name}</PersonName> 
                        <PhoneNumber>{$request.phone_to}</PhoneNumber> 
                    </Contact> 
                    <Address> 
                        <StreetLines>{$request.address_to}</StreetLines> 
                        <City>{$request.city_to}</City> 
                        <StateOrProvinceCode>{$request.state_to}</StateOrProvinceCode> 
                        <PostalCode>{$request.postcode_to}</PostalCode> 
                        <CountryCode>{$request.country_to}</CountryCode> 
                    </Address> 
                </Recipient>
                <RateRequestTypes>{$request.rate_type}</RateRequestTypes> 
                <PackageCount>1</PackageCount> 
                <RequestedPackageLineItems> 
                    <SequenceNumber>1</SequenceNumber> 
                    <GroupNumber>1</GroupNumber> 
                    <GroupPackageCount>1</GroupPackageCount> 
                    <Weight> 
                        <Units>{$request.weight_units}</Units> 
                        <Value>{$request.weight}</Value> 
                    </Weight> 
                    <Dimensions> 
                        <Length>{$request.length}</Length> 
                        <Width>{$request.width}</Width> 
                        <Height>{$request.height}</Height> 
                        <Units>{$request.length_code}</Units>
                    </Dimensions> 
                </RequestedPackageLineItems> 
            </RequestedShipment> 
        </RateRequest> 
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
