<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns:upss="http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:common="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0">
    <env:Header>
        <upss:UPSSecurity>
            <upss:UsernameToken>
                <upss:Username>{$request.ups_userid}</upss:Username>
                <upss:Password>{$request.ups_password}</upss:Password>
            </upss:UsernameToken>
            <upss:ServiceAccessToken>
                <upss:AccessLicenseNumber>{$request.ups_key}</upss:AccessLicenseNumber>
            </upss:ServiceAccessToken>
        </upss:UPSSecurity>
    </env:Header>
    <env:Body>
        <rate:RateRequest xmlns:rate="http://www.ups.com/XMLSchema/XOLTWS/Rate/v1.1" xmlns:common="http://www.ups.com/XMLSchema/XOLTWS/Common/v1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <common:Request>
                <common:RequestOption>Rate</common:RequestOption>
                <common:TransactionReference>
                    <common:CustomerContext>{$request.item_name}</common:CustomerContext>
                </common:TransactionReference>
            </common:Request>
            <rate:Shipment>
                <rate:Shipper>
                    <rate:Name>{$request.shipper_name}</rate:Name>
                    <rate:Address>
                        <rate:AddressLine>{$request.address_from}</rate:AddressLine>
                        <rate:City>{$request.city_from}</rate:City>
                        <rate:StateProvinceCode>{$request.state_from}</rate:StateProvinceCode>
                        <rate:PostalCode>{$request.postcode_from}</rate:PostalCode>
                        <rate:CountryCode>{$request.country_from}</rate:CountryCode>
                    </rate:Address>
                </rate:Shipper>
                <rate:ShipTo>
                    <rate:Name>{$request.recipient_name}</rate:Name>
                    <rate:Address>
                        <rate:AddressLine>{$request.address_to}</rate:AddressLine>
                        <rate:City>{$request.city_to}</rate:City>
                        <rate:StateProvinceCode>{$request.state_to}</rate:StateProvinceCode>
                        <rate:PostalCode>{$request.postcode_to}</rate:PostalCode>
                        <rate:CountryCode>{$request.country_to}</rate:CountryCode>
                    </rate:Address>
                </rate:ShipTo>
                <rate:ShipFrom>
                    <rate:Address>
                        <rate:AddressLine>{$request.address_from}</rate:AddressLine>
                        <rate:City>{$request.city_from}</rate:City>
                        <rate:StateProvinceCode>{$request.state_from}</rate:StateProvinceCode>
                        <rate:PostalCode>{$request.postcode_from}</rate:PostalCode>
                        <rate:CountryCode>{$request.country_from}</rate:CountryCode>
                    </rate:Address>
                </rate:ShipFrom>
                <rate:Service>
                    <rate:Code>{$request.service}</rate:Code>
                    <rate:Description>{$request.service_name}</rate:Description>
                </rate:Service>
                <rate:Package>
                    <rate:PackagingType>
                        <rate:Code>{$request.packaging}</rate:Code>
                        <rate:Description>{$request.packaging_name}</rate:Description>
                    </rate:PackagingType>
                    <rate:Dimensions>
                        <rate:UnitOfMeasurement>
                            <rate:Code>{$request.length_code}</rate:Code>
                            <rate:Description>{$request.length_code_name}</rate:Description>
                        </rate:UnitOfMeasurement>
                        <rate:Length>{$request.length}</rate:Length>
                        <rate:Width>{$request.width}</rate:Width>
                        <rate:Height>{$request.height}</rate:Height>
                    </rate:Dimensions>
                    <rate:PackageWeight>
                        <rate:UnitOfMeasurement>
                            <rate:Code>{$request.weight_units}</rate:Code>
                            <rate:Description>{$request.weight_units_name}</rate:Description>
                        </rate:UnitOfMeasurement>
                        <rate:Weight>{$request.weight}</rate:Weight>
                    </rate:PackageWeight>
                </rate:Package>
            </rate:Shipment>
        </rate:RateRequest>
    </env:Body>
</env:Envelope>
